name: ${project.name}
description: ${project.description}

main: tsp.headdb.HeadDB
version: ${project.version}
softdepend: ["Vault"]
api-version: 1.19
author: TheSilentPro (Silent)
spigot-id: 84967

commands:
  headdb:
    permission: headdb.admin
    usage: /headdb help
    description: Open the database
    aliases: ["hdb", "headdatabase", "headmenu"]

permissions:
  headdb.admin:
    default: op
    children:
      headdb.command.open: true
      headdb.command.search: true
      headdb.command.give: true
      headdb.command.update: true
      headdb.command.reload: true
      headdb.command.language: true
      headdb.command.settings: true
      headdb.command.texture: true
      headdb.favorites: true
      headdb.local: true
      headdb.category.*: true
  headdb.command.open:
    default: op
  headdb.command.search:
    default: op
  headdb.command.give:
    default: op
  headdb.command.update:
    default: op
  headdb.command.reload:
    default: op
  headdb.command.language:
    default: op
  headdb.command.settings:
    default: op
  headdb.command.texture:
    default: op
  headdb.favorites:
    default: op
  headdb.local:
    default: op
  headdb.category.*:
    default: op
